### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by ImKubass** [moritzlaube/parcel-transformer-html-datasrc#8]
Having issue running parcel after apliing transofrmer

```
npm i -D parcel-transformer-html-datasrc
```

added to `.parcelrc`
``` json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": ["parcel-transformer-html-datasrc", "..."]
  }
}
```

and also created `html-datasrc.config.json`

``` json
{
  "img": [
    "data-src",
    "data-srcset"
  ]
}
```

ten running 
```
parcel watch src/html/index.html
```

<img width="921" alt="Screenshot at Sep 25 10-11-16" src="https://user-images.githubusercontent.com/22158893/192134418-a9d5903f-d8c8-400c-87e2-3139c031a186.png">

Code:
```

🚨 Build failed.
TypeError: Cannot read properties of undefined (reading 'start')
    at /Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/codeframe/lib/codeframe.js:35920:27
    at Array.map (<anonymous>)
    at $796233c1fee0ccb8$export$2e2bcd8739ae039 (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/codeframe/lib/codeframe.js:35917:29)
    at $f02d6a9d30f55938$export$2e2bcd8739ae039 (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/utils/lib/index.js:32344:101)
    at async $7c213f7c22b64117$var$writeDiagnostic (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7435:121)
    at async $7c213f7c22b64117$export$12358408d9820617 (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/reporter-cli/lib/CLIReporter.js:7401:13)
    at async ReporterRunner.report (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/ReporterRunner.js:105:11)
    at async Parcel._build (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/Parcel.js:466:7)
    at async Parcel._startNextBuild (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/Parcel.js:298:24)
    at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/utils/lib/index.js:32433:13)
TypeError: Cannot read properties of undefined (reading 'start')
    at /Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/codeframe/lib/codeframe.js:35920:27
    at Array.map (<anonymous>)
    at $796233c1fee0ccb8$export$2e2bcd8739ae039 (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/codeframe/lib/codeframe.js:35917:29)
    at $f02d6a9d30f55938$export$2e2bcd8739ae039 (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/utils/lib/index.js:32344:101)
    at async Promise.all (index 0)
    at async $35f825eda3cd082d$export$2e2bcd8739ae039.emitError (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17114:35)
    at async Object.report (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:17330:32)
    at async ReporterRunner.report (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/ReporterRunner.js:105:11)
    at async Parcel._build (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/Parcel.js:466:7)
    at async Parcel._startNextBuild (/Users/jakubjetleb/Webs/rehabkka/node_modules/@parcel/core/lib/Parcel.js:298:24)

```

Any idea what is wrong?

**Comment by moritzlaube** [comment]
Hi @ImKubass! Would you be able to provide a minimum reproducible example? And besides, you don't necessarily need a config since `data-srcset` and `data-src` are default attributes on the image tag. Cheers

**Comment by ImKubass** [comment]
> Hi @ImKubass! Would you be able to provide a minimum reproducible example? And besides, you don't necessarily need a config since `data-srcset` and `data-src` are default attributes on the image tag. Cheers

@moritzlaube  I make clean repository with minimal setup
https://github.com/ImKubass/parcel-data-src
And same mistake appears

**Comment by ImKubass** [comment]
I probably figured it out.

✅
```
<img data-src="sample-01.jpg?width=800" alt=""/>
```

✅

```
<img src="sample-01.jpg?width=10" data-src="sample-01.jpg?width=800" alt=""/>
```

❌
```
<img src="" data-src="sample-01.jpg?width=800" alt=""/>
```

When src is empty it should endup with warning
Expected:
```
🚨 Build failed.

@parcel/transformer-html: 'src' should not be empty string
```
Acually happend:
```
🚨 Build failed.
TypeError: Cannot read properties of undefined (reading 'start')
```
